### ISSUE TITLE
Stricter author/signed-off-by match check

### ISSUE THREAD

**Issue by twpayne** [cilium/github-actions#18]
Currently, MLH checks for the presence of the string `Signed-off-by` in the commit message.

This check could be further improved by:

1. Checking that the string is of the correct format, e.g. it's followed by an email address.
2. The email address in the `Signed-off-by` matches the commit's author.

**Comment by pchaigno** [comment]
Why the second requirement?

**Comment by twpayne** [comment]
I think the author and the signed-off-by _should_ match, no?

**Comment by pchaigno** [comment]
I would expect them to match, but I don't see a reason to require it. In general, I'm in favor of reducing constraints on contributions to the strict minimum.

**Comment by twpayne** [comment]
Closing as stale.
