### ISSUE TITLE
Contributor push does not invalidate the `ready-to-merge` flag

### ISSUE THREAD

**Issue by joestringer** [cilium/github-actions#6]
Example PR:

https://github.com/cilium/cilium/pull/11323

![image](https://user-images.githubusercontent.com/1243336/81100333-3824f580-8ec1-11ea-8ed4-c5ac7ea3ada8.png)

In this case, PR was commented on then contributor re-pushed, but the `ready-to-merge` label remained. At this point we do not know whether either the reviewers or the CI are satisfied with the PR.

A couple of other observations:
* The PR was labeled "ready-to-merge" then a review added "changes requested", and the label was not removed.
* The earlier review added blocking checks due to "changes requested" which remains in the checks box at the bottom of this screenshot, but the maintainer's little helper isn't taking this into account.

**Comment by aanm** [comment]
fixed
